// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// CalcSurvFromNPMLE
NumericVector CalcSurvFromNPMLE(NumericVector probs, NumericVector points, NumericMatrix Tbull);
RcppExport SEXP CoxBinChange_CalcSurvFromNPMLE(SEXP probsSEXP, SEXP pointsSEXP, SEXP TbullSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Tbull(TbullSEXP);
    __result = Rcpp::wrap(CalcSurvFromNPMLE(probs, points, Tbull));
    return __result;
END_RCPP
}
// FindIntervalCalibCPP
NumericMatrix FindIntervalCalibCPP(NumericMatrix w, NumericMatrix wres);
RcppExport SEXP CoxBinChange_FindIntervalCalibCPP(SEXP wSEXP, SEXP wresSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type wres(wresSEXP);
    __result = Rcpp::wrap(FindIntervalCalibCPP(w, wres));
    return __result;
END_RCPP
}
// FindIntervalCPP
IntegerVector FindIntervalCPP(double point, NumericMatrix w);
RcppExport SEXP CoxBinChange_FindIntervalCPP(SEXP pointSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type point(pointSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type w(wSEXP);
    __result = Rcpp::wrap(FindIntervalCPP(point, w));
    return __result;
END_RCPP
}
// myF
double myF(double beta, NumericVector tm, LogicalVector event, NumericMatrix ps);
RcppExport SEXP CoxBinChange_myF(SEXP betaSEXP, SEXP tmSEXP, SEXP eventSEXP, SEXP psSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tm(tmSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type event(eventSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type ps(psSEXP);
    __result = Rcpp::wrap(myF(beta, tm, event, ps));
    return __result;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP CoxBinChange_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_hello_world());
    return __result;
END_RCPP
}
