# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CalcNablabeetaUbeta <- function(theta, tm, event, ps, Z, psDeriv) {
    .Call('ICcalib_CalcNablabeetaUbeta', PACKAGE = 'ICcalib', theta, tm, event, ps, Z, psDeriv)
}

CalcNablabeetaUgamma <- function(theta, tm, event, ps, Z, psDeriv) {
    .Call('ICcalib_CalcNablabeetaUgamma', PACKAGE = 'ICcalib', theta, tm, event, ps, Z, psDeriv)
}

CalcSurvFromNPMLE <- function(probs, points, Tbull) {
    .Call('ICcalib_CalcSurvFromNPMLE', PACKAGE = 'ICcalib', probs, points, Tbull)
}

CalcUbetabeeta <- function(beta, tm, event, ps, psDeriv) {
    .Call('ICcalib_CalcUbetabeeta', PACKAGE = 'ICcalib', beta, tm, event, ps, psDeriv)
}

CalcUbetabeetaRS <- function(beta, tm, event, ps, psDeriv) {
    .Call('ICcalib_CalcUbetabeetaRS', PACKAGE = 'ICcalib', beta, tm, event, ps, psDeriv)
}

Calcb <- function(beta, tm, event, ps) {
    .Call('ICcalib_Calcb', PACKAGE = 'ICcalib', beta, tm, event, ps)
}

CalcbZ <- function(theta, tm, event, ps, Z) {
    .Call('ICcalib_CalcbZ', PACKAGE = 'ICcalib', theta, tm, event, ps, Z)
}

CoxLogLik <- function(betagamma, tm, event, ps, Z) {
    .Call('ICcalib_CoxLogLik', PACKAGE = 'ICcalib', betagamma, tm, event, ps, Z)
}

CoxLogLikGrad <- function(theta, tm, event, ps, Z) {
    .Call('ICcalib_CoxLogLikGrad', PACKAGE = 'ICcalib', theta, tm, event, ps, Z)
}

CoxLogLikHess <- function(theta, tm, event, ps, Z) {
    .Call('ICcalib_CoxLogLikHess', PACKAGE = 'ICcalib', theta, tm, event, ps, Z)
}

CoxLogLikNoBeta <- function(gamma, tm, event, Z) {
    .Call('ICcalib_CoxLogLikNoBeta', PACKAGE = 'ICcalib', gamma, tm, event, Z)
}

CoxLogLikX <- function(beta, tm, event, ps) {
    .Call('ICcalib_CoxLogLikX', PACKAGE = 'ICcalib', beta, tm, event, ps)
}

FindIntervalCPP <- function(point, w) {
    .Call('ICcalib_FindIntervalCPP', PACKAGE = 'ICcalib', point, w)
}

FindIntervalCalibCPP <- function(w, wres) {
    .Call('ICcalib_FindIntervalCalibCPP', PACKAGE = 'ICcalib', w, wres)
}

FindIntervalCalibCPPvec <- function(w, wres) {
    .Call('ICcalib_FindIntervalCalibCPPvec', PACKAGE = 'ICcalib', w, wres)
}

myFmyHess <- function(beta, tm, event, ps) {
    .Call('ICcalib_myFmyHess', PACKAGE = 'ICcalib', beta, tm, event, ps)
}

