# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Calcb <- function(beta, tm, event, ps) {
    .Call('CoxBinChange_Calcb', PACKAGE = 'CoxBinChange', beta, tm, event, ps)
}

CalcSurvFromNPMLE <- function(probs, points, Tbull) {
    .Call('CoxBinChange_CalcSurvFromNPMLE', PACKAGE = 'CoxBinChange', probs, points, Tbull)
}

CalcUbetabeeta <- function(beta, tm, event, ps, psDeriv) {
    .Call('CoxBinChange_CalcUbetabeeta', PACKAGE = 'CoxBinChange', beta, tm, event, ps, psDeriv)
}

CalcUbetabeetaRS <- function(beta, tm, event, ps, psDeriv) {
    .Call('CoxBinChange_CalcUbetabeetaRS', PACKAGE = 'CoxBinChange', beta, tm, event, ps, psDeriv)
}

FindIntervalCalibCPP <- function(w, wres) {
    .Call('CoxBinChange_FindIntervalCalibCPP', PACKAGE = 'CoxBinChange', w, wres)
}

FindIntervalCPP <- function(point, w) {
    .Call('CoxBinChange_FindIntervalCPP', PACKAGE = 'CoxBinChange', point, w)
}

myF <- function(beta, tm, event, ps) {
    .Call('CoxBinChange_myF', PACKAGE = 'CoxBinChange', beta, tm, event, ps)
}

myFmyHess <- function(beta, tm, event, ps) {
    .Call('CoxBinChange_myFmyHess', PACKAGE = 'CoxBinChange', beta, tm, event, ps)
}

rcpp_hello_world <- function() {
    .Call('CoxBinChange_rcpp_hello_world', PACKAGE = 'CoxBinChange')
}

